I-100: "Navigation Node ready and publishing status periodically."
I-110: "task msg received"
E-111: "task msg malformed"
W-120: "targetpose ignored (busy)"
E-121: "targetpose malformed arrays"
E-122: "targetpose missing task id"
E-123: "targetpose empty path"
E-124: "targetpose tag mismatch"
I-125: "targetpose accepted"
I-130: "execution started"
D-131: "step moved to node"
I-132: "at pickup"
I-133: "pickup dwell"
I-134: "switched to drop path"
I-135: "at dropoff"
I-136: "task completed"
W-137: "task ended without drop"
E-138: "execution exception"
E-141: "status publish failed"
E-142: "check_goal exception"
I-150: "returned to idle"
I-200: "Task allocation request received"
E-201: "Invalid current node in Task Manager"
I-202: "Task queued (robot busy)"
I-203: "Task accepted and assigning"
E-204: "Invalid task id format"
E-208: "No path found to pickup"
E-211: "No path found to drop"
I-213: "TargetPose published"
I-220: "Assigning task from queue (robot idle)"
E-230: "TaskManager unexpected exception"
I-300: "StatusNode started"
I-311: "Robot Current Status Published"
E-301: "Failed to parse NavData"
E-302: "Failed to publish RobotStatus"

