trajectory_map:
  1: {"left": null, "right": null, "straight": 2}
  2: {"left": null, "right": null, "straight": 3}
  3: {"left": null, "right": null, "straight": 4}
  4: {"left": null, "right": null, "straight": 5}
  5: {"left": null, "right": null, "straight": 6}
  6: {"left": null, "right": null, "straight": 7}
  7: {"left": null, "right": 10, "straight": 8}
  8: {"left": null, "right": null, "straight": 9}
  9: {"left": null, "right": null, "straight": 10}
  10: {"left": null, "right": 15, "straight": 11}
  11: {"left": null, "right": null, "straight": 12}
  12: {"left": null, "right": null, "straight": 13}
  13: {"left": 20, "right": null, "straight": 14}
  14: {"left": null, "right": 17, "straight": 15}
  15: {"left": null, "right": null, "straight": 16}
  16: {"left": null, "right": null, "straight": 17}
  17: {"left": null, "right": null, "straight": 18}
  18: {"left": null, "right": null, "straight": 19}
  19: {"left": null, "right": null, "straight": 20}
  20: {"left": null, "right": 25, "straight": 21}
  21: {"left": null, "right": 24, "straight": 22}
  22: {"left": null, "right": null, "straight": 23}
  23: {"left": null, "right": null, "straight": 24}
  24: {"left": null, "right": null, "straight": 25}
  25: {"left": null, "right": null, "straight": 26}
  26: {"left": 33, "right": null, "straight": 27}
  27: {"left": null, "right": null, "straight": 28}
  28: {"left": null, "right": 31, "straight": 29}
  29: {"left": null, "right": null, "straight": 30}
  30: {"left": null, "right": 35, "straight": 31}
  31: {"left": null, "right": null, "straight": 32}
  32: {"left": null, "right": null, "straight": 33}
  33: {"left": null, "right": null, "straight": 34}
  34: {"left": null, "right": null, "straight": 35}
  35: {"left": null, "right": 38, "straight": 36}
  36: {"left": null, "right": null, "straight": 37}
  37: {"left": null, "right": null, "straight": 38}
  38: {"left": null, "right": null, "straight": 39}
  39: {"left": 46, "right": null, "straight": 40}
  40: {"left": null, "right": 45, "straight": 41}
  41: {"left": null, "right": null, "straight": 42}
  42: {"left": null, "right": 45, "straight": 43}
  43: {"left": null, "right": null, "straight": 44}
  44: {"left": null, "right": null, "straight": 45}
  45: {"left": null, "right": null, "straight": 46}
  46: {"left": null, "right": null, "straight": 47}
  47: {"left": null, "right": null, "straight": 48}
  48: {"left": null, "right": null, "straight": 49}
  49: {"left": null, "right": 52, "straight": 50}
  50: {"left": null, "right": 55, "straight": 51}
  51: {"left": null, "right": null, "straight": 52}
  52: {"left": 59, "right": null, "straight": 53}
  53: {"left": null, "right": null, "straight": 54}
  54: {"left": null, "right": null, "straight": 55}
  55: {"left": null, "right": null, "straight": 56}
  56: {"left": null, "right": 59, "straight": 57}
  57: {"left": null, "right": null, "straight": 58}
  58: {"left": null, "right": null, "straight": 59}
  59: {"left": null, "right": null, "straight": 60}
  60: {"left": null, "right": 65, "straight": 61}
  61: {"left": null, "right": null, "straight": 62}
  62: {"left": null, "right": null, "straight": 63}
  63: {"left": null, "right": 66, "straight": 64}
  64: {"left": null, "right": null, "straight": 65}
  65: {"left": 72, "right": null, "straight": 66}
  66: {"left": null, "right": null, "straight": 67}
  67: {"left": null, "right": null, "straight": 68}
  68: {"left": null, "right": null, "straight": 69}
  69: {"left": null, "right": null, "straight": 70}
  70: {"left": null, "right": 75, "straight": 71}
  71: {"left": null, "right": null, "straight": 72}
  72: {"left": null, "right": null, "straight": 73}
  73: {"left": null, "right": null, "straight": 74}
  74: {"left": null, "right": null, "straight": 75}
  75: {"left": null, "right": null, "straight": 76}
  76: {"left": null, "right": null, "straight": 77}
  77: {"left": null, "right": 80, "straight": 78}
  78: {"left": 85, "right": null, "straight": 79}
  79: {"left": null, "right": null, "straight": 80}
  80: {"left": null, "right": 85, "straight": 81}
  81: {"left": null, "right": null, "straight": 82}
  82: {"left": null, "right": null, "straight": 83}
  83: {"left": null, "right": null, "straight": 84}
  84: {"left": null, "right": 87, "straight": 85}
  85: {"left": null, "right": null, "straight": 86}
  86: {"left": null, "right": null, "straight": 87}
  87: {"left": null, "right": null, "straight": 88}
  88: {"left": null, "right": null, "straight": 89}
  89: {"left": null, "right": null, "straight": 90}
  90: {"left": null, "right": 95, "straight": 91}
  91: {"left": 98, "right": 94, "straight": 92}
  92: {"left": null, "right": null, "straight": 93}
  93: {"left": null, "right": null, "straight": 94}
  94: {"left": null, "right": null, "straight": 95}
  95: {"left": null, "right": null, "straight": 96}
  96: {"left": null, "right": null, "straight": 97}
  97: {"left": null, "right": null, "straight": 98}
  98: {"left": null, "right": null, "straight": 99}
  99: {"left": null, "right": null, "straight": 100}
  100: {"left": null, "right": null, "straight": 1}
